### ISSUE TITLE
Move constants and other globals into enviroment varialbes

### ISSUE THREAD

**Issue by Gim949** [umbchackers/hardModeCode#5]
Specifically these parts:
```js
const PORT = 3000;
const IP = "127.0.0.1";
const JAVASCRIPT = "javascript";
const PYTHON = "python";
```
can be placed into their own environment file(s) or 'constants' file

**Comment by reesdraminski** [comment]
I think best practice is something like:
```javascript
const PORT = process.env.PORT || 3000;
```
so that there is a value just in case the .env file disappears, but I agree environment variables are a good way to go.

As for the language-related constants, that was just to prevent me from using magic strings, so it could be defined at the function level in getFileExtension() because that's the only time those constants are actually used.
